services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Basilicom\PathFormatterBundle\DependencyInjection\PimcoreAdapter:

  Basilicom\PathFormatterBundle\Formatter\ExpressionFunctions:

  Basilicom\PathFormatterBundle\Formatter\PatternRenderer:

  Basilicom\PathFormatterBundle\Command\DebugPathFormatterCommand:

  Basilicom\PathFormatterBundle\DependencyInjection\BasilicomPathFormatter:
    public: true
